import { AuthProvider } from "@/components/auth-provider"
import DashboardShell from "../../src/components/dashboard-shell"
import { DashboardTitleProvider } from "../../src/components/dashboard-title-context"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function DashboardLayout({ children, title = "Documents" }: { children: React.ReactNode, title?: string }) {
  return (
    <AuthProvider>
      <DashboardTitleProvider>
        <DashboardShell title={title}>{children}</DashboardShell>
      </DashboardTitleProvider>
    </AuthProvider>
  )
}
